FROM swift:5.4.3-amazonlinux2 AS builder

RUN yum update && yum install -y libcurl-devel libxml2-devel

RUN git clone https://github.com/realm/SwiftLint.git
WORKDIR /SwiftLint
RUN git checkout 0.43.1
ENV SWIFT_FLAGS="--configuration release -Xswiftc -static-stdlib -Xlinker -lCFURLSessionInterface -Xlinker -lCFXMLInterface -Xlinker -lcurl -Xlinker -lxml2"
RUN swift build ${SWIFT_FLAGS} --product swiftlint && install -v `swift build ${SWIFT_FLAGS} --show-bin-path`/swiftlint /usr/bin


FROM swift:5.4.3-amazonlinux2-slim

RUN yum update && yum install -y java-1.8.0-openjdk shadow-utils adduser && adduser -s /bin/false -u 2004 docker

COPY --from=builder /usr/bin/swiftlint /usr/bin/swiftlint
COPY --from=builder /usr/lib/libsourcekitdInProc.so /usr/lib/libsourcekitdInProc.so

COPY docs /docs
COPY target/universal/stage/ /workdir/
RUN chmod +x /workdir/bin/codacy-swiftlint
USER docker
WORKDIR /src
ENTRYPOINT ["/workdir/bin/codacy-swiftlint"]
