FROM norionomura/swiftlint:0.61.0_swift-6.1

RUN apt-get update && apt-get install -y openjdk-17-jre-headless

COPY docs /docs
COPY target/universal/stage/ /workdir/
COPY doc-generator/target/universal/stage/ /doc-generator
RUN (cd workdir && /doc-generator/bin/doc-generator)
RUN chmod +x /workdir/bin/codacy-swiftlint
RUN adduser --uid 2004 --disabled-password --gecos "" docker
USER docker
WORKDIR /src
ENTRYPOINT ["/workdir/bin/codacy-swiftlint"]
