version: 2.1

orbs:
  codacy: codacy/base@8.1.0
  codacy_plugins_test: codacy/plugins-test@1.1.1

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: publish_docker_local
          cmd: |
            sbt "scalafmtCheckAll;
                 scalafmtSbtCheck;
                 graalvm-native-image:packageBin"
            docker build -t $CIRCLE_PROJECT_REPONAME:latest -f Dockerfile.dev .
            # Run doc-generator
            sudo sbt doc-generator/run
            # Update docker image with generated docs
            docker build -t $CIRCLE_PROJECT_REPONAME:latest .
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          cache_prefix: sbt-cache-27102021-3
          requires:
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - publish_docker_local
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - plugins_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - codacy/publish_docker
